site_name: FastAPI | 2 Projetos | TDD | Docker
repo_url: https://github.com/elzasimoes/2024-fast-api-async
repo_name: elzasimoes/2024-fast-api-async

theme:
  name: "material"
  language: pt-BR

watch:
   - api

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [api]