site_name: Fast API - 2024
repo_url: https://github.com/elzasimoes/2024-fast-api-async
repo_name: elzasimoes/2024-fast-api-async

theme:
  name: "material"
  language: pt-BR

watch:
   - api

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [api]